
import { bootstrapApplication } from '@angular/platform-browser';
import { provideAnimations } from '@angular/platform-browser/animations';
import { AppComponent } from './app/app';
import { provideRouter } from '@angular/router';
import { routes } from './app/app.routes';
import { importProvidersFrom } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { withInterceptors } from '@angular/common/http';
import { authInterceptor } from './app/core/interceptors/auth.interceptor';

// 👇 Lucide
import { BrushCleaning, EyeOff, LucideAngularModule, ArrowLeft } from 'lucide-angular';
import {
  Heart,
  HeartOff,
  History,
  BarChart3,
  Scale,
  Search,
  X,
  Trash2,
  Trash,
  Map,
  Moon,
  Sun,
  Funnel,
  Euro,
  ChevronsDown,
  ChevronsUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Ruler,
  Sparkles,
  Layers,
  Flame,
  MapPin,
  RefreshCcw,
  LogOut,
  Columns3,
  Eye,
  Navigation2,
  ListOrdered,
  House,
  Compass,
  Info,
  Shield,
  ExternalLink,
  Calculator,
  Footprints,
  Bike,
  Car,
  Clock,
  Route,
  ArrowLeftRight,
  Wrench,
  Trees,
  TrainFront,
  GraduationCap,
  Cross,
  ShoppingCart,
} from 'lucide-angular';
import { Legend } from 'chart.js';

bootstrapApplication(AppComponent, {
  providers: [
    provideRouter(routes),
    provideAnimations(),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        Heart,
        HeartOff,
        History,
        BarChart3,
        Scale,
        Search,
        X,
        Trash2,
        Trash,
        Map,
        Moon,
        Sun,
        Funnel,
        Euro,
        ChevronsDown,
        ChevronsUp,
        Ruler,
        Sparkles,
        Layers,
        Flame,
        MapPin,
        RefreshCcw,
        BrushCleaning,
        LogOut,
        Columns3,
        Eye,
        EyeOff,
        Navigation2,
        ListOrdered,
        House,
        Compass,
        Info,
        Shield,
        ArrowLeft,
        ExternalLink,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        Calculator,
        Footprints,
        Bike,
        Car,
        Clock,
        Route,
        ArrowLeftRight,
        Wrench,
        Trees,
        TrainFront,
        GraduationCap,
        Cross,
        ShoppingCart,
      })
    ),
  ],
}).catch((err) => console.error(err));
